name: Run SAST
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      - name: Run Gosec Security Scanner
        working-directory: ./backend
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec ./...