name: Trufflehog Secret Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trufflehog:
    name: Run Trufflehog Secret Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trufflehog
        uses: trufflesecurity/trufflehog@v3.91.1
        with:
          scanArguments: --no-update --json .